### ISSUE TITLE
BinarySearchTree

### ISSUE THREAD

**Issue by rusdevops** [moskanka/BinarySearchTree#1]
@moskanka 
- [x] не используемая переменная [thisNode](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L33)
- [x] дублирование кода [здесь](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L36-L38) и [здесь](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L48-L51)
- [x] не правильная реализация метода [insert](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L45) на примере `{5, 4, 5}`
- [x] не правильная реализация метода [find](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L71)
- [x] утечка памяти [здесь](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L118)
- [x] избыточность кода [здесь](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L127), [здесь](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L145-L146) и [здесь](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L155)
- [x] не корректная реализация операторов [ввода](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L105) и [вывода](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L97)
- [x] отсутствие проверки возвращаемого значения [здесь](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L135-L136)
- [x] избыточность кода отладочной информацией [здесь](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L76), [здесь](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L83), [здесь](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L90), [здесь](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L101) и [здесь](https://github.com/moskanka/3semester/blob/99096dba8a79998cfaac6fb0507a1c686632b9d4/BinTree/main.cpp#L108)

**Comment by annafragor** [comment]
@rusdevops 
1) А в чем именно заключается некорректность операторов ввода/вывода?
2) Строку `std::cout << "tree is empty\n";` в операторе вывода я все же думаю оставить, тк что-то же должен увидеть пользователь, если дерево пусто. От остальных лишних строк, несущих отладочную информацию, избавилась.
3) Метод insert я исправила. Просто я не подумала о том, что элементы не могут повторяться. (надеюсь в этом была ошибка))
4) Метод find тоже поправила, надеюсь верно.

**Comment by rusdevops** [comment]
@moskanka 
- некорректность оператора вывода заключается в не однозначном представление дерева, а именно отсутствует возможность определить, кто является родителем, а кто потомком в дереве.
- ваше второе утверждение нарушает принцип разделения ответственности. для исправления этого реализуйте для класса `BinarySearchTree` метод `bool empty() const`, а в теле функции `main` перед вызовом оператора вывода проверяйте дерево на отсутствие элементов, в случае если дерево пустое выводите строку `std::cout << "tree is empty" << std::endl`  на экран.

**Comment by annafragor** [comment]
@rusdevops 
1) Я немного поправила оператор вывода. Стало лучше, или нужно сделать как-то по-другому?
2) empty() реализовала

**Comment by rusdevops** [comment]
В операторах ввода, необходимо проверять результат их вызова. Для примера: `if(cin >> size)`.

**Comment by rusdevops** [comment]
Наиболее удобной реализацией оператора вывода в `std::ostream&` будет симметричный обход с права на лево (`R-С-L`).

А результатом вызова будет следующий: (для `BinarySearchTree{2, 1, 3, 5, 4, 7}`)

```
---7
--5
---4
-3
2
-1
```

**Comment by rusdevops** [comment]
- [x] Не корректная реализация метода `insert`. 
  - [x] Увеличение алгоритмической сложности в два раза. 
  - [x] В случае если элемент находиться в дереве метод должен возвращать `false`.
